### PR TITLE
fixed errors and added subscription button plan details

### PR DESCRIPTION
**Pull request by sonyy-m**

### CODE REVIEW

**Review by sofiya02 — CHANGES_REQUESTED** [review]
no dropdown list for payment button or subscription button

**Comment by sonyy-m** [comment]
> no dropdown list for payment button or subscription button

Please deactivate the visual composer plugin and activate again

**Comment by sofiya02** [comment]
> > no dropdown list for payment button or subscription button
> 
> Please deactivate the visual composer plugin and activate again

Still the error persist and also in fresh setup

**Review by sofiya02 — APPROVED** [review]
LGTM

**Pull request merged**
